plugin:
    name: 'travis.rolodex::lang.plugin.name'
    description: 'travis.rolodex::lang.plugin.description'
    author: 'Scott Travis'
    icon: oc-icon-users
    homepage: 'https://github.com/swt83/php-october-rolodex'
navigation:
    rolodex:
        label: 'travis.rolodex::lang.plugin.name'
        url: travis/rolodex/contacts
        icon: oc-icon-users
        iconSvg: 'plugins/travis/rolodex/assets/img/icon.png'
        permissions:
            - travis.rolodex.manage_rolodex
        sideMenu:
            contacts:
                label: Contacts
                url: travis/rolodex/contacts
                icon: icon-list
permissions:
    travis.rolodex.manage_rolodex:
        tab: 'travis.rolodex::lang.plugin.name'
        label: 'Manage Rolodex'
