plugin:
    name: 'travis.team::lang.plugin.name'
    description: 'travis.team::lang.plugin.description'
    author: 'Scott Travis'
    icon: oc-icon-users
    homepage: 'https://github.com/swt83/php-october-team'
navigation:
    team:
        label: 'travis.team::lang.plugin.name'
        url: travis/team/members
        icon: icon-users
        iconSvg: 'plugins/travis/team/assets/img/icon.png'
        permissions:
            - travis.team.manage_team
        sideMenu:
            members:
                label: Members
                url: travis/team/members
                icon: icon-list
permissions:
    travis.team.manage_team:
        tab: 'travis.team::lang.plugin.name'
        label: 'Manage Teams'
