title: Contacts
modelClass: Travis\Rolodex\Models\Contact
list: $/travis/rolodex/models/contact/columns.yaml
recordUrl: 'travis/rolodex/contacts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
