title: Members
modelClass: Travis\Team\Models\Member
list: $/travis/team/models/member/columns.yaml
recordUrl: 'travis/team/members/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
