name: Members
form: $/travis/team/models/member/fields.yaml
modelClass: Travis\Team\Models\Member
defaultRedirect: travis/team/members
create:
    redirect: 'travis/team/members/update/:id'
    redirectClose: travis/team/members
update:
    redirect: travis/team/members
    redirectClose: travis/team/members
